/* 
 *  This script was generated by Netsparker 5.6.2.27219, at 21/02/2020 13:50:04 
 *  For more information about Custom Script Checks and samples, please refer to documentation: 
 *  https://www.netsparker.com/support/custom-security-checks-scripting/ 
 */
var attacks = [{
    id: 'd8a2826d-6080-4d67-8937-d7ce97ba1fad',
    name: 'ThemeGrill Demo Importer Database Wipe and Auth Bypass Issue',
    attack: 'wp-content/plugins/themegrill-demo-importer/readme.txt',
}];

function analyze(context, response) {
    // Research: https://www.webarxsecurity.com/critical-issue-in-themegrill-demo-importer/
    // All versions of the plugin: https://raw.githubusercontent.com/themegrill/themegrill-demo-importer/master/CHANGELOG.txt
    var vulnerableVers = ["1.6.1", "1.6.0", "1.5.9", "1.5.8", "1.5.7", "1.5.7", "1.5.6", "1.5.5", "1.5.4", "1.5.3", "1.5.3", "1.5.1", "1.5.0", "1.4.3", "1.4.2", "1.4.1", "1.4.0", "1.3.4"];
    var ThemeGrillVersionRegEx = /Stable tag: ([0-9.]{1,})/;
    var ThemeGrillVersion = response.Body.match(ThemeGrillVersionRegEx);
    if (ThemeGrillVersion) {
        if (vulnerableVers.indexOf(ThemeGrillVersion[1]) > -1) {
            var vuln = new Vulnerability("5f33c567-9262-4c93-84a9-a73895d862dc");
            vuln.CustomFields.Add("Detected Version:", ThemeGrillVersion[1]);
            return vuln;
        }
    }
}
