/* 
*  This Per-Directory Security Check script was generated by Invicti Standard 23.6.0.40861, at 09-Jun-23 10:38:30 AM 
*  For more information about Custom Script Checks and samples, please refer to documentation: 
*  https://www.invicti.com/support/custom-security-checks-scripting/ 
*/ 

var attacks = [
    {
        id: 'cad2836f-85f9-4437-b293-2bdf6864166c',
        name: 'Wordpress XML-RPC Detection',
        attack: 'xmlrpc.php',
    }
];

function createRawRequestBody(url, body) {
    var re = /(https?:\/\/)([^:^\/]*)(:\d*)(.*)?/;
    const capture = url.match(re);
    host =  capture[2].toString() + capture[3].toString();
    origin = capture[1].toString() + host;
    uri = capture[4].toString();
    var length = body.length;
    // prepare raw request    
    var raw =  `POST ${uri} HTTP/1.1
Content-Type: text/xml
Host: ${host}
Content-Length: ${length.toString()}

${body}`;
        return raw;
}

function analyze(context, response) {
    if (response.Body.indexOf('XML-RPC server accepts POST requests only.') > -1 && response.StatusCode == 405) {
        var body = `<methodCall><methodName>demo.sayHello</methodName><params></params></methodCall>`
        var postRequest = createRawRequestBody(response.Uri.toString(), body);
        var postResponse = invicti.requestRaw(response.Uri.toString(), postRequest, false);

        if (postResponse.Body.indexOf('<string>Hello!</string>') > -1) {
            return new Vulnerability('f8b2e048-1d5a-4c3d-a17b-e9c047999126');    
        }
    }
}